const $=id=>document.getElementById(id), yen=n=>'¥'+new Intl.NumberFormat('ja-JP').format(Math.max(0,Math.round(n)));
const A=[{v:1e7,l:'1,000万'},{v:1e8,l:'1億'},{v:3e8,l:'3億'},{v:1e9,l:'10億'}];
const P=[['👨‍👩‍👦','家族'],['🕊️','自由'],['✈️','旅行'],['🌱','挑戦']];
const F=[['🌿','庭'],['💻','書斎'],['🧸','遊び部屋'],['🛁','大きな風呂'],['🍳','アイランドK'],['🚗','2台駐車']];
let S={amount:3e8,priority:'家族',features:new Set(['庭','書斎','遊び部屋']),home:null,work:null,real:null,day:null};
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('on'));$(id).classList.add('on');scrollTo(0,0)}
function amountLabel(){return A.find(x=>x.v===S.amount)?.l||''}
function renderAmounts(){ $('amounts').innerHTML=A.map(x=>`<button class="${x.v===S.amount?'sel':''}" data-v="${x.v}">${x.l}</button>`).join(''); $('jackpotText').textContent=amountLabel(); document.querySelectorAll('#amounts button').forEach(b=>b.onclick=()=>{S.amount=+b.dataset.v;renderAmounts()}) }
function renderPriority(){ $('priority').innerHTML=P.map(x=>`<button class="priority ${S.priority===x[1]?'sel':''}" data-v="${x[1]}"><span class="ico">${x[0]}</span><b>${x[1]}</b></button>`).join(''); document.querySelectorAll('.priority').forEach(b=>b.onclick=()=>{S.priority=b.dataset.v;renderPriority()}) }
function renderFeatures(){ $('features').innerHTML=F.map(x=>`<button class="feature ${S.features.has(x[1])?'sel':''}" data-v="${x[1]}"><span class="ico">${x[0]}</span>${x[1]}</button>`).join(''); document.querySelectorAll('.feature').forEach(b=>b.onclick=()=>{let v=b.dataset.v;S.features.has(v)?S.features.delete(v):S.features.add(v);renderFeatures()}) }
function budgetOptions(){ let opts=S.amount<=1e7?[300,500,700,1000]:S.amount<=1e8?[4000,6000,8000,10000]:S.amount<=3e8?[7000,9000,12000,15000]:[10000,15000,20000,30000]; $('budget').innerHTML=opts.map(v=>`<option value="${v*1e4}">${v>=10000?(v/10000)+'億円':v.toLocaleString()+'万円'}</option>`).join(''); $('budget').selectedIndex=Math.min(1,opts.length-1) }
function makeCandidates(){let cap=+$('budget').value,base=Math.min(cap,S.amount*.42),area=$('area').value||'希望エリア',size=+$('size').value,type=$('type').value,feat=[...S.features];let list=[
 {name:'家族時間を中心にした家',price:Math.round(base*.82),area,type,size,ldk:27,rooms:'4LDK＋書斎',tags:feat.slice(0,4),kind:'balance'},
 {name:'広さを優先したゆとりの家',price:Math.round(base*.95),area,type,size:size+20,ldk:31,rooms:'5LDK＋プレイルーム',tags:[...new Set([...feat,'収納多め'])].slice(0,5),kind:'wide'},
 {name:'せっかくなら、まで盛った家',price:Math.round(Math.min(cap,base*1.08)),area,type,size:size+35,ldk:34,rooms:'5LDK＋書斎＋趣味室',tags:[...new Set([...feat,'ホテル風浴室','上質家具'])].slice(0,6),kind:'luxury'}
]; if(S.real) list.unshift({name:S.real.title,price:S.real.price,area:'実在の候補',type:'持ち込み',size:'—',ldk:'—',rooms:'URLから持ち込み',tags:['実在候補','自分で見つけた'],kind:'real',url:S.real.url}); return list.slice(0,3)}
function sceneHTML(c){return `<div class="scene ${c.kind==='real'?'real':''}"><span class="sun"></span><span class="house"></span><span class="roof"></span><span class="door"></span><span class="win"></span><span class="tree"></span><span class="label">${c.kind==='real'?'あなたが見つけた候補':c.area}</span></div>`}
function renderResults(){let list=makeCandidates(); $('results').innerHTML=list.map((c,i)=>`<article class="property">${sceneHTML(c)}<div class="propBody"><div class="price">${yen(c.price)}</div><h3>${c.name}</h3><div class="specGrid"><div class="spec"><b>${c.type}</b><small>タイプ</small></div><div class="spec"><b>${c.size}${typeof c.size==='number'?'㎡':''}</b><small>広さ</small></div><div class="spec"><b>${c.ldk}${typeof c.ldk==='number'?'畳':''}</b><small>LDK</small></div></div><div class="tags">${c.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><button class="choose" data-i="${i}">この暮らしを選ぶ</button></div></article>`).join('');document.querySelectorAll('.choose').forEach(b=>b.onclick=()=>{let c=list[+b.dataset.i];S.home=c;preparePurchase()})}
function preparePurchase(){let total=Math.round(S.home.price*1.07);S.home.total=total;S.home.remaining=S.amount-total;$('purchaseTitle').textContent=S.home.name;$('beforeMoney').textContent=yen(S.amount);$('afterMoney').textContent=yen(S.home.remaining);$('purchaseVisual').innerHTML='';show('s3')}
function overlay(){let ov=$('impactOverlay');ov.innerHTML=`<div><strong>3つのことが変わりました</strong><p>家を決めたことで、働き方・車・家族時間の条件が更新されます。</p></div>`;ov.classList.add('on');setTimeout(()=>{ov.classList.remove('on');show('s4');renderWorld('world',false);renderRipple();renderSurprise('surprise',false)},1400)}
function renderWorld(id,withWork){let rem=withWork&&S.work?S.home.remaining-S.work.reserve:S.home.remaining;$(id).innerHTML=`<div class="worldScene"><div class="caption"><small>あなたの当選後</small><b>${S.home.area}</b></div><div class="home">🏡</div><div class="car">🚗</div><div class="plane">✈️</div><div class="desk">💻</div></div><div class="balanceCard"><small>残り資産</small><strong>${yen(rem)}</strong><small>${withWork&&S.work?'働き方の余裕予算も確保済み':'住まいを決めた直後'}</small></div><div class="lifeGrid"><div class="lifeNode done"><div class="ico">🏡</div><b>住まい</b><small>${S.home.name}</small></div><div class="lifeNode ${withWork?'done':'hot'}"><div class="ico">💼</div><b>仕事</b><small>${withWork?S.work.name:'次に決める'}</small></div><div class="lifeNode hot"><div class="ico">👨‍👩‍👦</div><b>家族</b><small>${withWork?'平日時間が増えた':'庭・広さで休日が変化'}</small></div><div class="lifeNode"><div class="ico">✈️</div><b>旅行</b><small>${withWork?'長期旅行が現実的に':'まだ未設定'}</small></div><div class="lifeNode"><div class="ico">🚗</div><b>車</b><small>${S.features.has('2台駐車')?'2台持ちも可能':'暮らしに合わせて'}</small></div><div class="lifeNode"><div class="ico">🌱</div><b>挑戦</b><small>${withWork?'週の余白を使える':'まだ未設定'}</small></div></div>`}
function renderRipple(){let flows=[];flows.push('🏡 家を決定');if(S.features.has('2台駐車'))flows.push('🚗 車の選択肢↑');if(S.features.has('庭'))flows.push('👨‍👩‍👦 休日の過ごし方↑');flows.push('💼 通勤条件を再考');$('ripple').innerHTML=`<div class="impactCard"><div class="impactTitle">この決断の波紋</div><div class="impactFlow">${flows.map((x,i)=>`${i?'<i>→</i>':''}<span>${x}</span>`).join('')}</div></div>`}
function surpriseText(afterWork=false){if(!afterWork){if(S.home.remaining>1.5e8)return ['まだ“2年の自由”を先に買えます','家を買った後でも、2年間まったく焦らず働き方を変える余裕があります。'];if(S.priority==='旅行')return ['家を買っても、長期旅行はまだ主役にできます','毎年1か月の旅行を続ける予算を別枠で置く選択もできます。'];return ['家の次は「時間」を買うと、景色がもっと変わります','週3勤務にすると、この家で過ごす平日そのものが増えます。']}else{if(S.work.days<=3)return ['平日に“家族で一泊”ができる生活になりました','週2日以上の余白があるので、週末を待たずに小旅行できます。'];return ['仕事を残したまま、安心を厚くする道もあります','今の収入をある程度残せるなら、資産を大きく減らさず旅行や挑戦へ回せます。']}}
function renderSurprise(id,after){let [a,b]=surpriseText(after);$(id).innerHTML=`<div class="surprise"><div class="ey">✦ こんな未来もあります</div><strong>${a}</strong><p>${b}</p></div>`}
const WORK=[{name:'今まで通り',days:5,reserve:0,copy:'生活は安定。資産をほぼ減らさず次の夢へ。'},{name:'週4にする',days:4,reserve:6000000,copy:'毎週1日、家族か自分に返す。'},{name:'週3にする',days:3,reserve:15000000,copy:'平日が2日空く。旅行や挑戦が現実になる。'},{name:'1年間休む',days:0,reserve:7000000,copy:'まず1年、人生を急がない。'}];
function renderWorks(){ $('works').innerHTML=WORK.map((w,i)=>`<button class="work ${S.work===w?'sel':''}" data-i="${i}"><span class="days"><span><b>${w.days}</b><small>日 / 週</small></span></span><span class="workCopy"><b>${w.name}</b><small>${w.copy}</small><span class="week">${['月','火','水','木','金','土','日'].map((d,j)=>`<span class="${j>=w.days&&j<5?'off':''}">${d}</span>`).join('')}</span></span><span class="reserve">${w.reserve?yen(w.reserve)+'\n余裕予算':'追加予算\nなし'}</span></button>`).join(''); document.querySelectorAll('.work').forEach(b=>b.onclick=()=>{S.work=WORK[+b.dataset.i];renderWorks();$('applyWork').disabled=false}) }
function renderDayChoices(){let opts=[['☕','何もしない朝'],['👨‍👩‍👦','家族と過ごす'],['💻','自分の仕事を作る'],['🚗','ふらっと出かける']];$('dayChoices').innerHTML=opts.map(x=>`<button class="dayChoice ${S.day===x[1]?'sel':''}" data-v="${x[1]}"><b>${x[0]} ${x[1]}</b><small>この過ごし方で1日を見る</small></button>`).join('');document.querySelectorAll('.dayChoice').forEach(b=>b.onclick=()=>{S.day=b.dataset.v;renderDayChoices();renderTimeline();$('finish').disabled=false})}
function renderTimeline(){let mood=S.day||'何もしない朝',events=mood.includes('家族')?[['8:30','ゆっくり朝食','急いで出勤しなくていい。'],['10:30','近所へ散歩','平日の空いている街を家族で歩く。'],['12:30','外でランチ','混雑を気にせず好きな店へ。'],['15:00','家の庭で遊ぶ','選んだ家の価値が、時間として返ってくる。'],['20:30','明日も余白','週末を待たなくていい。']]:mood.includes('仕事')?[['9:00','コーヒーとPC','誰にも急かされず、自分のアイデアを開く。'],['11:00','2時間だけ集中','売れるかより、作りたいものを優先。'],['13:00','家で昼食','通勤がないだけで1日が長い。'],['15:30','今日はここまで','時間を使い切らない。'],['21:00','家族時間','仕事と生活が競合しない。']]:[['9:30','予定なし','目覚ましより少し遅く起きる。'],['11:00',mood,'「暇」ではなく、選べる時間。'],['13:00','好きな昼食','平日の余白を味わう。'],['16:00','家でのんびり','買った家をちゃんと使う。'],['21:00','明日を急がない','当選額が「時間」に変わっている。']];$('timeline').innerHTML=`<div class="timeline">${events.map(e=>`<div class="timeRow"><div class="time">${e[0]}</div><div class="event"><b>${e[1]}</b><p>${e[2]}</p></div></div>`).join('')}</div>`}
function final(){renderWorld('finalWorld',true);let [a,b]=surpriseText(true);$('finalSuggestion').innerHTML=`<div class="surprise"><div class="ey">✦ この人生から次に広がるもの</div><strong>${a}</strong><p>${b}</p></div>`;show('s8')}
renderAmounts();renderPriority();renderFeatures();budgetOptions();
$('start').onclick=()=>{budgetOptions();show('s1')};
$('useReal').onclick=()=>{let title=$('realTitle').value.trim(),p=parseFloat($('realPrice').value);if(!title||!p){alert('候補名と価格を入力してください');return}S.real={title,price:p*1e4,url:$('realUrl').value.trim()};alert('候補に追加しました。下の条件も必要なら調整してください。')};
$('search').onclick=()=>{renderResults();show('s2')};$('editSearch').onclick=()=>show('s1');$('cancelPurchase').onclick=()=>show('s2');$('confirmPurchase').onclick=overlay;
$('toWork').onclick=()=>{renderWorks();show('s5')};$('applyWork').onclick=()=>{renderWorld('world2',true);renderSurprise('surprise2',true);show('s6')};$('toDay').onclick=()=>{renderDayChoices();renderTimeline();show('s7')};$('finish').onclick=final;
$('payIntent').onclick=()=>{localStorage.setItem('atattara-v09-pay-intent','yes');$('payFeedback').classList.add('on')};$('restart').onclick=()=>{localStorage.removeItem('atattara-v09-pay-intent');location.reload()};